import { explore } from '@lib/lens/explore-publications';
import { Layout } from 'components/Layout';
import { ProfileContext, TagsFilterContext } from 'components';

import { TagsFilter } from 'components/TagsFilter';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState, useContext } from 'react';
import ExplorerCard from 'components/ExplorerCard';

const App: NextPage = () => {
  const [publications, setPublications] = useState<any[]>([]);
  const [hydrationLoading, setHydrationLoading] = useState(true);
  useEffect(() => {
    setHydrationLoading(false);
  }, []);

  const { tags } = useContext(TagsFilterContext);

  useEffect(() => {
    explore({ tags }).then((data) => setPublications(data.items));
  }, [tags]);

  if (hydrationLoading) {
    return <h1>Loading...</h1>;
  }

  return (
    <div className="bg-white">
      <Head>
        <title>Lenstags</title>
        <meta name="description" content="Generated by Gardeners" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <Layout
        title={'Lenstags | Home'}
        pageDescription={'TODO: Descripcion de la pagina'}
      >
        <div className="container mx-auto h-64 w-11/12 py-10 px-6 md:w-4/5 ">
          {/* <Profile /> */}
          {/* <Tabs /> */}
          <div className="mb-3">
            <TagsFilter />
          </div>

          <div className="container mx-auto px-4 md:px-12">
            <div className="-mx-1 flex flex-wrap lg:-mx-4">
              {publications
                ? publications.map((post, index) => (
                    <ExplorerCard post={post} key={index} />
                  ))
                : null}
            </div>
          </div>
          <div className="h-auto w-full">{/* <Pagination /> */}</div>
        </div>
      </Layout>
    </div>
  );
};

export default App;
